// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Title field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Primary CTA field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.primary_cta
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_cta: prismic.KeyTextField;

  /**
   * Secondary CTA field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.secondary_cta
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_cta: prismic.KeyTextField;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default hero section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: Hero section with title, subtitle, and CTAs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *PopularRoutes → Default → Primary*
 */
export interface PopularRoutesSliceDefaultPrimary {
  /**
   * Title field in *PopularRoutes → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: popular_routes.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * View All field in *PopularRoutes → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: popular_routes.default.primary.view_all
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  view_all: prismic.KeyTextField;
}

/**
 * Default variation for PopularRoutes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default popular routes section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PopularRoutesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PopularRoutesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PopularRoutes*
 */
type PopularRoutesSliceVariation = PopularRoutesSliceDefault;

/**
 * PopularRoutes Shared Slice
 *
 * - **API ID**: `popular_routes`
 * - **Description**: Popular route links and labels
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PopularRoutesSlice = prismic.SharedSlice<
  "popular_routes",
  PopularRoutesSliceVariation
>;

/**
 * Primary content in *RichTextSection → Default → Primary*
 */
export interface RichTextSectionSliceDefaultPrimary {
  /**
   * Title field in *RichTextSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *RichTextSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for RichTextSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default rich text section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichTextSection*
 */
type RichTextSectionSliceVariation = RichTextSectionSliceDefault;

/**
 * RichTextSection Shared Slice
 *
 * - **API ID**: `rich_text_section`
 * - **Description**: Simple title and rich text content block
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSectionSlice = prismic.SharedSlice<
  "rich_text_section",
  RichTextSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.WriteClientConfig,
    ): prismic.WriteClient;
  }

  interface CreateMigration {
    (): prismic.Migration;
  }

  namespace Content {
    export type {
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      PopularRoutesSlice,
      PopularRoutesSliceDefaultPrimary,
      PopularRoutesSliceVariation,
      PopularRoutesSliceDefault,
      RichTextSectionSlice,
      RichTextSectionSliceDefaultPrimary,
      RichTextSectionSliceVariation,
      RichTextSectionSliceDefault,
    };
  }
}
