/* tslint:disable */
/* eslint-disable */
/**
 * JSONPlaceholder API
 * Typed OpenAPI contract for the public JSONPlaceholder fake REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Photo
 */
export interface Photo {
    /**
     * 
     * @type {number}
     * @memberof Photo
     */
    albumId: number;
    /**
     * 
     * @type {number}
     * @memberof Photo
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Photo
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Photo
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof Photo
     */
    thumbnailUrl: string;
}

/**
 * Check if a given object implements the Photo interface.
 */
export function instanceOfPhoto(value: object): value is Photo {
    if (!('albumId' in value) || value['albumId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('thumbnailUrl' in value) || value['thumbnailUrl'] === undefined) return false;
    return true;
}

export function PhotoFromJSON(json: any): Photo {
    return PhotoFromJSONTyped(json, false);
}

export function PhotoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Photo {
    if (json == null) {
        return json;
    }
    return {
        
        'albumId': json['albumId'],
        'id': json['id'],
        'title': json['title'],
        'url': json['url'],
        'thumbnailUrl': json['thumbnailUrl'],
    };
}

export function PhotoToJSON(json: any): Photo {
    return PhotoToJSONTyped(json, false);
}

export function PhotoToJSONTyped(value?: Photo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'albumId': value['albumId'],
        'id': value['id'],
        'title': value['title'],
        'url': value['url'],
        'thumbnailUrl': value['thumbnailUrl'],
    };
}

