/* tslint:disable */
/* eslint-disable */
/**
 * JSONPlaceholder API
 * Typed OpenAPI contract for the public JSONPlaceholder fake REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostPatch
 */
export interface PostPatch {
    /**
     * 
     * @type {number}
     * @memberof PostPatch
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof PostPatch
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof PostPatch
     */
    body?: string;
}

/**
 * Check if a given object implements the PostPatch interface.
 */
export function instanceOfPostPatch(value: object): value is PostPatch {
    return true;
}

export function PostPatchFromJSON(json: any): PostPatch {
    return PostPatchFromJSONTyped(json, false);
}

export function PostPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'title': json['title'] == null ? undefined : json['title'],
        'body': json['body'] == null ? undefined : json['body'],
    };
}

export function PostPatchToJSON(json: any): PostPatch {
    return PostPatchToJSONTyped(json, false);
}

export function PostPatchToJSONTyped(value?: PostPatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'title': value['title'],
        'body': value['body'],
    };
}

