/* tslint:disable */
/* eslint-disable */
/**
 * JSONPlaceholder API
 * Typed OpenAPI contract for the public JSONPlaceholder fake REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SecurityTokenResponse
 */
export interface SecurityTokenResponse {
    /**
     * 
     * @type {number}
     * @memberof SecurityTokenResponse
     */
    expiresInSeconds: number;
    /**
     * 
     * @type {boolean}
     * @memberof SecurityTokenResponse
     */
    reused: boolean;
}

/**
 * Check if a given object implements the SecurityTokenResponse interface.
 */
export function instanceOfSecurityTokenResponse(value: object): value is SecurityTokenResponse {
    if (!('expiresInSeconds' in value) || value['expiresInSeconds'] === undefined) return false;
    if (!('reused' in value) || value['reused'] === undefined) return false;
    return true;
}

export function SecurityTokenResponseFromJSON(json: any): SecurityTokenResponse {
    return SecurityTokenResponseFromJSONTyped(json, false);
}

export function SecurityTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecurityTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'expiresInSeconds': json['expiresInSeconds'],
        'reused': json['reused'],
    };
}

export function SecurityTokenResponseToJSON(json: any): SecurityTokenResponse {
    return SecurityTokenResponseToJSONTyped(json, false);
}

export function SecurityTokenResponseToJSONTyped(value?: SecurityTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expiresInSeconds': value['expiresInSeconds'],
        'reused': value['reused'],
    };
}

