/* tslint:disable */
/* eslint-disable */
/**
 * JSONPlaceholder API
 * Typed OpenAPI contract for the public JSONPlaceholder fake REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Album,
    AlbumFromJSON,
    AlbumToJSON,
} from '../models/Album';

export interface GetAlbumRequest {
    id: number;
}

export interface ListAlbumsRequest {
    userId?: number;
}

/**
 * AlbumsApi - interface
 * 
 * @export
 * @interface AlbumsApiInterface
 */
export interface AlbumsApiInterface {
    /**
     * Creates request options for getAlbum without sending the request
     * @param {number} id 
     * @throws {RequiredError}
     * @memberof AlbumsApiInterface
     */
    getAlbumRequestOpts(requestParameters: GetAlbumRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlbumsApiInterface
     */
    getAlbumRaw(requestParameters: GetAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Album>>;

    /**
     */
    getAlbum(requestParameters: GetAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Album>;

    /**
     * Creates request options for listAlbums without sending the request
     * @param {number} [userId] 
     * @throws {RequiredError}
     * @memberof AlbumsApiInterface
     */
    listAlbumsRequestOpts(requestParameters: ListAlbumsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} [userId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlbumsApiInterface
     */
    listAlbumsRaw(requestParameters: ListAlbumsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Album>>>;

    /**
     */
    listAlbums(requestParameters: ListAlbumsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Album>>;

}

/**
 * 
 */
export class AlbumsApi extends runtime.BaseAPI implements AlbumsApiInterface {

    /**
     * Creates request options for getAlbum without sending the request
     */
    async getAlbumRequestOpts(requestParameters: GetAlbumRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAlbum().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/albums/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAlbumRaw(requestParameters: GetAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Album>> {
        const requestOptions = await this.getAlbumRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlbumFromJSON(jsonValue));
    }

    /**
     */
    async getAlbum(requestParameters: GetAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Album> {
        const response = await this.getAlbumRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAlbums without sending the request
     */
    async listAlbumsRequestOpts(requestParameters: ListAlbumsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/albums`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listAlbumsRaw(requestParameters: ListAlbumsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Album>>> {
        const requestOptions = await this.listAlbumsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AlbumFromJSON));
    }

    /**
     */
    async listAlbums(requestParameters: ListAlbumsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Album>> {
        const response = await this.listAlbumsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
