/* tslint:disable */
/* eslint-disable */
/**
 * JSONPlaceholder API
 * Typed OpenAPI contract for the public JSONPlaceholder fake REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Photo,
    PhotoFromJSON,
    PhotoToJSON,
} from '../models/Photo';

export interface ListAlbumPhotosRequest {
    id: number;
}

export interface ListPhotosRequest {
    albumId?: number;
}

/**
 * PhotosApi - interface
 * 
 * @export
 * @interface PhotosApiInterface
 */
export interface PhotosApiInterface {
    /**
     * Creates request options for listAlbumPhotos without sending the request
     * @param {number} id 
     * @throws {RequiredError}
     * @memberof PhotosApiInterface
     */
    listAlbumPhotosRequestOpts(requestParameters: ListAlbumPhotosRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PhotosApiInterface
     */
    listAlbumPhotosRaw(requestParameters: ListAlbumPhotosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Photo>>>;

    /**
     */
    listAlbumPhotos(requestParameters: ListAlbumPhotosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Photo>>;

    /**
     * Creates request options for listPhotos without sending the request
     * @param {number} [albumId] 
     * @throws {RequiredError}
     * @memberof PhotosApiInterface
     */
    listPhotosRequestOpts(requestParameters: ListPhotosRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} [albumId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PhotosApiInterface
     */
    listPhotosRaw(requestParameters: ListPhotosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Photo>>>;

    /**
     */
    listPhotos(requestParameters: ListPhotosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Photo>>;

}

/**
 * 
 */
export class PhotosApi extends runtime.BaseAPI implements PhotosApiInterface {

    /**
     * Creates request options for listAlbumPhotos without sending the request
     */
    async listAlbumPhotosRequestOpts(requestParameters: ListAlbumPhotosRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listAlbumPhotos().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/albums/{id}/photos`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listAlbumPhotosRaw(requestParameters: ListAlbumPhotosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Photo>>> {
        const requestOptions = await this.listAlbumPhotosRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PhotoFromJSON));
    }

    /**
     */
    async listAlbumPhotos(requestParameters: ListAlbumPhotosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Photo>> {
        const response = await this.listAlbumPhotosRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listPhotos without sending the request
     */
    async listPhotosRequestOpts(requestParameters: ListPhotosRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['albumId'] != null) {
            queryParameters['albumId'] = requestParameters['albumId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/photos`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listPhotosRaw(requestParameters: ListPhotosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Photo>>> {
        const requestOptions = await this.listPhotosRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PhotoFromJSON));
    }

    /**
     */
    async listPhotos(requestParameters: ListPhotosRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Photo>> {
        const response = await this.listPhotosRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
