/* tslint:disable */
/* eslint-disable */
/**
 * JSONPlaceholder API
 * Typed OpenAPI contract for the public JSONPlaceholder fake REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Post,
    PostFromJSON,
    PostToJSON,
} from '../models/Post';
import {
    type PostInput,
    PostInputFromJSON,
    PostInputToJSON,
} from '../models/PostInput';
import {
    type PostPatch,
    PostPatchFromJSON,
    PostPatchToJSON,
} from '../models/PostPatch';

export interface CreatePostRequest {
    postInput: PostInput;
}

export interface DeletePostRequest {
    id: number;
}

export interface GetPostRequest {
    id: number;
}

export interface ListPostsRequest {
    userId?: number;
}

export interface PatchPostRequest {
    id: number;
    postPatch: PostPatch;
}

export interface UpdatePostRequest {
    id: number;
    postInput: PostInput;
}

/**
 * PostsApi - interface
 * 
 * @export
 * @interface PostsApiInterface
 */
export interface PostsApiInterface {
    /**
     * Creates request options for createPost without sending the request
     * @param {PostInput} postInput 
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    createPostRequestOpts(requestParameters: CreatePostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {PostInput} postInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    createPostRaw(requestParameters: CreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Post>>;

    /**
     */
    createPost(requestParameters: CreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Post>;

    /**
     * Creates request options for deletePost without sending the request
     * @param {number} id 
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    deletePostRequestOpts(requestParameters: DeletePostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    deletePostRaw(requestParameters: DeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     */
    deletePost(requestParameters: DeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for getPost without sending the request
     * @param {number} id 
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    getPostRequestOpts(requestParameters: GetPostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    getPostRaw(requestParameters: GetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Post>>;

    /**
     */
    getPost(requestParameters: GetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Post>;

    /**
     * Creates request options for listPosts without sending the request
     * @param {number} [userId] 
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    listPostsRequestOpts(requestParameters: ListPostsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} [userId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    listPostsRaw(requestParameters: ListPostsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Post>>>;

    /**
     */
    listPosts(requestParameters: ListPostsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Post>>;

    /**
     * Creates request options for patchPost without sending the request
     * @param {number} id 
     * @param {PostPatch} postPatch 
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    patchPostRequestOpts(requestParameters: PatchPostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} id 
     * @param {PostPatch} postPatch 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    patchPostRaw(requestParameters: PatchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Post>>;

    /**
     */
    patchPost(requestParameters: PatchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Post>;

    /**
     * Creates request options for updatePost without sending the request
     * @param {number} id 
     * @param {PostInput} postInput 
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    updatePostRequestOpts(requestParameters: UpdatePostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} id 
     * @param {PostInput} postInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostsApiInterface
     */
    updatePostRaw(requestParameters: UpdatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Post>>;

    /**
     */
    updatePost(requestParameters: UpdatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Post>;

}

/**
 * 
 */
export class PostsApi extends runtime.BaseAPI implements PostsApiInterface {

    /**
     * Creates request options for createPost without sending the request
     */
    async createPostRequestOpts(requestParameters: CreatePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postInput'] == null) {
            throw new runtime.RequiredError(
                'postInput',
                'Required parameter "postInput" was null or undefined when calling createPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/posts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostInputToJSON(requestParameters['postInput']),
        };
    }

    /**
     */
    async createPostRaw(requestParameters: CreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Post>> {
        const requestOptions = await this.createPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostFromJSON(jsonValue));
    }

    /**
     */
    async createPost(requestParameters: CreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Post> {
        const response = await this.createPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deletePost without sending the request
     */
    async deletePostRequestOpts(requestParameters: DeletePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/posts/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deletePostRaw(requestParameters: DeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.deletePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async deletePost(requestParameters: DeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.deletePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPost without sending the request
     */
    async getPostRequestOpts(requestParameters: GetPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/posts/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getPostRaw(requestParameters: GetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Post>> {
        const requestOptions = await this.getPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostFromJSON(jsonValue));
    }

    /**
     */
    async getPost(requestParameters: GetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Post> {
        const response = await this.getPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listPosts without sending the request
     */
    async listPostsRequestOpts(requestParameters: ListPostsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/posts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listPostsRaw(requestParameters: ListPostsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Post>>> {
        const requestOptions = await this.listPostsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PostFromJSON));
    }

    /**
     */
    async listPosts(requestParameters: ListPostsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Post>> {
        const response = await this.listPostsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchPost without sending the request
     */
    async patchPostRequestOpts(requestParameters: PatchPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchPost().'
            );
        }

        if (requestParameters['postPatch'] == null) {
            throw new runtime.RequiredError(
                'postPatch',
                'Required parameter "postPatch" was null or undefined when calling patchPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/posts/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PostPatchToJSON(requestParameters['postPatch']),
        };
    }

    /**
     */
    async patchPostRaw(requestParameters: PatchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Post>> {
        const requestOptions = await this.patchPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostFromJSON(jsonValue));
    }

    /**
     */
    async patchPost(requestParameters: PatchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Post> {
        const response = await this.patchPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updatePost without sending the request
     */
    async updatePostRequestOpts(requestParameters: UpdatePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updatePost().'
            );
        }

        if (requestParameters['postInput'] == null) {
            throw new runtime.RequiredError(
                'postInput',
                'Required parameter "postInput" was null or undefined when calling updatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/posts/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PostInputToJSON(requestParameters['postInput']),
        };
    }

    /**
     */
    async updatePostRaw(requestParameters: UpdatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Post>> {
        const requestOptions = await this.updatePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostFromJSON(jsonValue));
    }

    /**
     */
    async updatePost(requestParameters: UpdatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Post> {
        const response = await this.updatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
