/* tslint:disable */
/* eslint-disable */
/**
 * JSONPlaceholder API
 * Typed OpenAPI contract for the public JSONPlaceholder fake REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type SecurityTokenResponse,
    SecurityTokenResponseFromJSON,
    SecurityTokenResponseToJSON,
} from '../models/SecurityTokenResponse';

/**
 * SecurityTokenApi - interface
 * 
 * @export
 * @interface SecurityTokenApiInterface
 */
export interface SecurityTokenApiInterface {
    /**
     * Creates request options for createSecurityToken without sending the request
     * @throws {RequiredError}
     * @memberof SecurityTokenApiInterface
     */
    createSecurityTokenRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SecurityTokenApiInterface
     */
    createSecurityTokenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SecurityTokenResponse>>;

    /**
     */
    createSecurityToken(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SecurityTokenResponse>;

}

/**
 * 
 */
export class SecurityTokenApi extends runtime.BaseAPI implements SecurityTokenApiInterface {

    /**
     * Creates request options for createSecurityToken without sending the request
     */
    async createSecurityTokenRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/security-token`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async createSecurityTokenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SecurityTokenResponse>> {
        const requestOptions = await this.createSecurityTokenRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SecurityTokenResponseFromJSON(jsonValue));
    }

    /**
     */
    async createSecurityToken(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SecurityTokenResponse> {
        const response = await this.createSecurityTokenRaw(initOverrides);
        return await response.value();
    }

}
