// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero_section: dynamic(() => import("./HeroSection")),
  popular_routes: dynamic(() => import("./PopularRoutes")),
  rich_text: dynamic(() => import("./RichText")),
  rich_text_section: dynamic(() => import("./RichTextSection")),
};
