import {
  existsSync,
  rmSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";

type SliceModel = {
  id: string;
  name: string;
};

type SliceEntry = {
  directoryName: string;
  model: SliceModel;
};

const pulledSlicesRoot = path.resolve("src/slices");
const cmsSlicesRoot = path.resolve("../../packages/cms/src/slices");
const generatedAppRoots = [
  path.resolve("src/app/home-page"),
  path.resolve("src/app/slice-simulator"),
];

function main() {
  const pulledSlices = getPulledSlices();

  if (pulledSlices.length === 0) {
    console.log("No pulled Prismic slices found to sync.");
    return;
  }

  for (const slice of pulledSlices) {
    syncSliceModel(slice);
    ensureCmsSliceComponent(slice);
  }

  writeCmsSliceIndex();
  cleanupGeneratedPrismicScaffold();

  console.log(`Synced ${pulledSlices.length} Prismic slice model(s) to packages/cms.`);
}

function getPulledSlices(): SliceEntry[] {
  if (!existsSync(pulledSlicesRoot)) {
    return [];
  }

  return readdirSync(pulledSlicesRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => {
      const modelPath = path.join(pulledSlicesRoot, entry.name, "model.json");

      if (!existsSync(modelPath)) {
        return null;
      }

      return {
        directoryName: entry.name,
        model: JSON.parse(readFileSync(modelPath, "utf8")) as SliceModel,
      };
    })
    .filter((entry): entry is SliceEntry => entry !== null)
    .sort((left, right) => left.directoryName.localeCompare(right.directoryName));
}

function syncSliceModel(slice: SliceEntry) {
  const sourcePath = path.join(pulledSlicesRoot, slice.directoryName, "model.json");
  const targetDirectory = path.join(cmsSlicesRoot, slice.directoryName);
  const targetPath = path.join(targetDirectory, "model.json");

  mkdirSync(targetDirectory, { recursive: true });

  const nextContents = `${readFileSync(sourcePath, "utf8").trimEnd()}\n`;
  const previousContents = existsSync(targetPath)
    ? readFileSync(targetPath, "utf8")
    : null;

  if (previousContents !== nextContents) {
    writeFileSync(targetPath, nextContents);
  }
}

function ensureCmsSliceComponent(slice: SliceEntry) {
  const componentPath = path.join(cmsSlicesRoot, slice.directoryName, "index.tsx");

  if (existsSync(componentPath)) {
    return;
  }

  const componentContents = `import type { SharedSlice } from "@prismicio/client";
import type { SliceComponentProps } from "@prismicio/react";

type ${slice.directoryName}Props = SliceComponentProps<SharedSlice<"${slice.model.id}">>;

const ${slice.directoryName} = ({ slice }: ${slice.directoryName}Props) => {
  return (
    <section
      data-slice-type={slice.slice_type}
      data-slice-variation={slice.variation}
    >
      Placeholder component for {slice.slice_type} (variation: {slice.variation})
      slices.
    </section>
  );
};

export default ${slice.directoryName};
`;

  writeFileSync(componentPath, componentContents);
}

function writeCmsSliceIndex() {
  const sliceEntries = readdirSync(cmsSlicesRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => {
      const modelPath = path.join(cmsSlicesRoot, entry.name, "model.json");

      if (!existsSync(modelPath)) {
        return null;
      }

      return {
        directoryName: entry.name,
        model: JSON.parse(readFileSync(modelPath, "utf8")) as SliceModel,
      };
    })
    .filter((entry): entry is SliceEntry => entry !== null)
    .sort((left, right) => left.directoryName.localeCompare(right.directoryName));

  const imports = sliceEntries
    .map(
      (slice) =>
        `  ${slice.model.id}: dynamic(() => import("./${slice.directoryName}")),`,
    )
    .join("\n");

  const indexContents = `// Code generated by Prismic sync. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
${imports}
};
`;

  writeFileSync(path.join(cmsSlicesRoot, "index.ts"), indexContents);
}

function cleanupGeneratedPrismicScaffold() {
  if (existsSync(pulledSlicesRoot)) {
    rmSync(pulledSlicesRoot, { force: true, recursive: true });
  }

  for (const generatedAppRoot of generatedAppRoots) {
    if (existsSync(generatedAppRoot)) {
      rmSync(generatedAppRoot, { force: true, recursive: true });
    }
  }
}

main();
