server:
  port: 4002

app:
  prismic:
    repository-name: ${PRISMIC_REPOSITORY_NAME:}
    access-token: ${PRISMIC_ACCESS_TOKEN:}
    cache-ttl-seconds: ${PRISMIC_JAVA_CACHE_TTL_SECONDS:300}
    label-document-types:
      - flight_search
      - flight_select
      - passenger
